# Generated by Django 2.2.3 on 2019-07-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='description',
            new_name='casts',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='meta_score',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='votes',
        ),
    ]
